import { getDb } from '../core/db.js';

export function exportAsClaudeMd(tags?: string[]): string {
  const db = getDb();

  // Get all verified facts
  const facts = db.prepare(`
    SELECT r.type, r.summary, r.confidence,
           s.name as source_name, t.name as target_name,
           s.type as source_type, t.type as target_type,
           r.access_tags
    FROM relation r
    JOIN entity s ON r.source_id = s.id
    JOIN entity t ON r.target_id = t.id
    WHERE r.verified = 1 AND r.valid_until IS NULL
    ORDER BY r.confidence DESC
  `).all() as Array<{
    type: string; summary: string | null; confidence: number;
    source_name: string; target_name: string;
    source_type: string; target_type: string;
    access_tags: string;
  }>;

  // Filter by access tags
  const filtered = tags && tags.length > 0
    ? facts.filter(r => {
        const factTags = JSON.parse(r.access_tags || '["all"]') as string[];
        return factTags.includes('all') || factTags.some(t => tags!.includes(t));
      })
    : facts;

  // Find user entity for name
  const userEntity = db.prepare(
    "SELECT name FROM entity WHERE type = 'person' ORDER BY created_at ASC LIMIT 1"
  ).get() as { name: string } | undefined;
  const userName = userEntity?.name || 'User';

  const lines: string[] = [];
  lines.push(`# User Context — ${userName}`);
  lines.push('');
  lines.push(`> Auto-generated by me.md-kg from ${filtered.length} verified facts.`);
  lines.push('');

  // Group by category
  const identity = filtered.filter(f => ['has_name', 'has_nationality', 'has_property', 'has_role'].includes(f.type));
  const work = filtered.filter(f => ['works_at', 'manages', 'created', 'founded', 'has_role'].includes(f.type));
  const places = filtered.filter(f => ['lives_in', 'moved_to', 'born_in'].includes(f.type));
  const people = filtered.filter(f => ['knows', 'has_doctor', 'is_doctor_of'].includes(f.type));
  const preferences = filtered.filter(f => ['prefers', 'values', 'believes'].includes(f.type));
  const skills = filtered.filter(f => ['has_skill', 'speaks', 'expert_in'].includes(f.type));

  const renderSection = (title: string, items: typeof filtered) => {
    if (items.length === 0) return;
    lines.push(`## ${title}`);
    lines.push('');
    for (const item of items) {
      lines.push(`- ${item.summary || `${item.source_name} → ${item.type} → ${item.target_name}`}`);
    }
    lines.push('');
  };

  renderSection('Who I Am', identity);
  renderSection('Work & Career', work);
  renderSection('Where I Live', places);
  renderSection('People', people);
  renderSection('Preferences & Values', preferences);
  renderSection('Skills & Languages', skills);

  // Remaining uncategorized
  const categorized = new Set([...identity, ...work, ...places, ...people, ...preferences, ...skills]);
  const other = filtered.filter(f => !categorized.has(f));
  renderSection('Other', other);

  return lines.join('\n');
}
