import { getDb } from '../core/db.js';

interface ExportSection {
  title: string;
  facts: Array<{ summary: string; confidence: number; source: string; target: string }>;
}

export function exportAsMarkdown(tags?: string[]): string {
  const db = getDb();

  const facts = getVerifiedFacts(db, tags);
  const sections = organizeFacts(facts);
  const entityCount = (db.prepare('SELECT COUNT(*) as count FROM entity').get() as { count: number }).count;

  const lines: string[] = [];
  lines.push('# me.md — Personal Knowledge');
  lines.push('');
  lines.push('> Auto-generated from verified knowledge graph');
  lines.push(`> Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push(`> ${facts.length} verified facts across ${entityCount} entities`);
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const section of sections) {
    if (section.facts.length === 0) continue;
    lines.push(`## ${section.title}`);
    lines.push('');
    for (const fact of section.facts) {
      lines.push(`- ${fact.summary || `${fact.source} → ${fact.target}`}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by [me.md-kg](https://github.com/oleksiinikitin/me.md-kg)*');
  lines.push('');

  return lines.join('\n');
}

function getVerifiedFacts(db: ReturnType<typeof getDb>, tags?: string[]) {
  const query = `
    SELECT r.type, r.summary, r.confidence,
           s.name as source_name, s.type as source_type,
           t.name as target_name, t.type as target_type,
           r.access_tags
    FROM relation r
    JOIN entity s ON r.source_id = s.id
    JOIN entity t ON r.target_id = t.id
    WHERE r.verified = 1 AND r.valid_until IS NULL
    ORDER BY r.confidence DESC
  `;

  const results = db.prepare(query).all() as Array<{
    type: string; summary: string | null; confidence: number;
    source_name: string; source_type: string;
    target_name: string; target_type: string;
    access_tags: string;
  }>;

  // Filter by access tags if specified
  if (tags && tags.length > 0) {
    return results.filter(r => {
      const factTags = JSON.parse(r.access_tags || '["all"]') as string[];
      return factTags.includes('all') || factTags.some(t => tags.includes(t));
    });
  }

  return results;
}

function organizeFacts(facts: Array<{
  type: string; summary: string | null; confidence: number;
  source_name: string; source_type: string;
  target_name: string; target_type: string;
}>): ExportSection[] {
  const sectionMap: Record<string, ExportSection> = {
    identity: { title: 'Identity & Background', facts: [] },
    work: { title: 'Work & Career', facts: [] },
    relationships: { title: 'People & Relationships', facts: [] },
    places: { title: 'Places & Living', facts: [] },
    preferences: { title: 'Preferences & Values', facts: [] },
    skills: { title: 'Skills & Expertise', facts: [] },
    services: { title: 'Tools & Services', facts: [] },
    health: { title: 'Health & Wellness', facts: [] },
    other: { title: 'Other', facts: [] },
  };

  for (const fact of facts) {
    const f = {
      summary: fact.summary || `${fact.source_name} → ${fact.type} → ${fact.target_name}`,
      confidence: fact.confidence,
      source: fact.source_name,
      target: fact.target_name,
    };

    const section = categorizeRelation(fact.type, fact.source_type, fact.target_type);
    (sectionMap[section] || sectionMap.other).facts.push(f);
  }

  return Object.values(sectionMap);
}

function categorizeRelation(relationType: string, sourceType: string, targetType: string): string {
  if (['works_at', 'has_role', 'manages', 'created', 'founded'].includes(relationType)) return 'work';
  if (['lives_in', 'moved_to', 'born_in'].includes(relationType)) return 'places';
  if (['knows', 'has_doctor', 'is_doctor_of', 'family', 'friend'].includes(relationType)) return 'relationships';
  if (['prefers', 'values', 'believes'].includes(relationType)) return 'preferences';
  if (['has_skill', 'speaks', 'expert_in'].includes(relationType)) return 'skills';
  if (['uses', 'uses_service', 'subscribes'].includes(relationType)) return 'services';
  if (targetType === 'doctor' || relationType.includes('health') || relationType.includes('medical')) return 'health';
  if (['has_name', 'has_nationality', 'has_property'].includes(relationType)) return 'identity';
  return 'other';
}
